sudo: required

dist: bionic

branches:
  only:
    - master
    - next
    - opentransport
    - kube-migration
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

before_install:
  - export TZ=Europe/Bucharest

install: true

services:
  - docker

notifications:
  slack: opentransportro:lxVFa6wGTFd0FaSUujY1zLJX
jobs:
  include:
    - stage: test
      env: LINT=1
      node_js: '10'
      script:
        - yarn install
        - yarn lint
    - stage: test
      env: FLOW=1
      node_js: '10'
      script:
        - yarn install
        - test/flow.sh
      if: NOT branch IN (opentransport, "kube-migration")
    - stage: test
      env: UNIT=1
      node_js: '10'
      script:
        - yarn install
        - yarn run test-coverage
        - yarn run test-report
      if: NOT branch IN (opentransport, "kube-migration")
    - stage: visual
      env: VISUAL=chrome
      node_js: '10'
      script: test/visual.sh
      if: NOT branch IN (opentransport, "kube-migration")
    - stage: visual
      env: VISUAL=firefox
      node_js: '10'
      script: test/visual.sh
      if: NOT branch IN (opentransport, "kube-migration")
    - stage: visual
      env: VISUAL=safari
      node_js: '10'
      script: test/visual.sh
      if: NOT branch IN (opentransport, "kube-migration")
    - stage: visual
      env: VISUAL=edge
      node_js: '10'
      script: test/visual.sh
      if: NOT branch IN (opentransport, "kube-migration")

    - stage: build and deploy container
      node_js: '10'
      script:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
        - test/deploy.sh
