sudo: required

dist: trusty

branches:
  only:
    - master
    - next
    - opentransport
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

before_install:
  - export TZ=Europe/Bucharest

install: true

services:
  - docker

jobs:
  include:
    - stage: test
      env: LINT=1
      node_js: '10'
      script:
        - yarn install
        - yarn lint
    - stage: test
      env: FLOW=1
      node_js: '10'
      script:
        - yarn install
        - test/flow.sh
      if: branch != opentransport
    - stage: test
      env: UNIT=1
      node_js: '10'
      script:
        - yarn install
        - yarn run test-coverage
        - yarn run test-report
      if: branch != opentransport
    - stage: visual
      env: VISUAL=chrome
      node_js: '10'
      script: test/visual.sh
      if: branch != opentransport
    - stage: visual
      env: VISUAL=firefox
      node_js: '10'
      script: test/visual.sh
      if: branch != opentransport
    - stage: visual
      env: VISUAL=safari
      node_js: '10'
      script: test/visual.sh
      if: branch != opentransport
    - stage: visual
      env: VISUAL=edge
      node_js: '10'
      script: test/visual.sh
      if: branch != opentransport

    - stage: build and deploy container
      node_js: '10'
      script: test/deploy.sh
